ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4D0)
      DOUBLE PRECISION NL
      PARAMETER(NL=2D0)

      DOUBLE PRECISION MDL_MW,MDL_MZ,MDL_MH,MDL_MB,MDL_MT,MDL_MTA

      COMMON/MASSES/ MDL_MW,MDL_MZ,MDL_MH,MDL_MB,MDL_MT,MDL_MTA


      DOUBLE PRECISION MDL_WW,MDL_WT,MDL_WZ,MDL_WH

      COMMON/WIDTHS/ MDL_WW,MDL_WT,MDL_WZ,MDL_WH


      DOUBLE COMPLEX GC_1, GC_2, GC_3, GC_5, GC_35, GC_36, GC_50,
     $  GC_53, GC_57, GC_58, GC_72, GC_81, GC_100

      COMMON/COUPLINGS/ GC_1, GC_2, GC_3, GC_5, GC_35, GC_36, GC_50,
     $  GC_53, GC_57, GC_58, GC_72, GC_81, GC_100

