C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2) - P(1,3)
C     
      SUBROUTINE VSS1_0_WW_FD(V1, S2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      COMPLEX*16 S2(*)
      COMPLEX*16 S3(*)
      COMPLEX*16 TMP7
      COMPLEX*16 TMP8
      COMPLEX*16 V1(*)
      INTEGER*4 I
      COMPLEX*16 VERTEX
      P2(0) = DBLE(S2(1))
      P2(1) = DBLE(S2(2))
      P2(2) = DIMAG(S2(2))
      P2(3) = DIMAG(S2(1))
      P3(0) = DBLE(S3(1))
      P3(1) = DBLE(S3(2))
      P3(2) = DIMAG(S3(2))
      P3(3) = DIMAG(S3(1))
      TMP7 = (V1(3)*P2(0)-V1(4)*P2(1)-V1(5)*P2(2)-V1(6)*P2(3))
      TMP8 = (V1(3)*P3(0)-V1(4)*P3(1)-V1(5)*P3(2)-V1(6)*P3(3))
      VERTEX = COUP*S2(7)*S3(7)*(-CI*(TMP7)+CI*(TMP8))
      END


