C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,3)
C     
      SUBROUTINE VSV2_2_WW_FD(V1, V3, COUP, M2, W2,S2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP
      REAL*8 M2
      REAL*8 P2(0:3)
      COMPLEX*16 S2(7)
      COMPLEX*16 TMP3
      COMPLEX*16 V1(*)
      COMPLEX*16 V3(*)
      REAL*8 W2
      COMPLEX*16 DENOM
      INTEGER*4 I
      S2(1) = +V1(1)+V3(1)
      S2(2) = +V1(2)+V3(2)
      P2(0) = -DBLE(S2(1))
      P2(1) = -DBLE(S2(2))
      P2(2) = -DIMAG(S2(2))
      P2(3) = -DIMAG(S2(1))
      DO I = 3, 7
        S2(I) = CZERO
      ENDDO
      TMP3 = (V3(3)*V1(3)-V3(4)*V1(4)-V3(5)*V1(5)-V3(6)*V1(6))
      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
      S2(7)= DENOM*CI * TMP3
      CALL MULTIPLY_PROPAGATOR_FACTOR(S2,M2, S2)
      END


