C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,3)
C     
      SUBROUTINE VSV2_3_WW_FD(V1, S2, COUP, M3, W3,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP
      REAL*8 M3
      REAL*8 P3(0:3)
      COMPLEX*16 S2(*)
      COMPLEX*16 V1(*)
      COMPLEX*16 V3(7)
      REAL*8 W3
      COMPLEX*16 DENOM
      INTEGER*4 I
      V3(1) = +V1(1)+S2(1)
      V3(2) = +V1(2)+S2(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))
      DO I = 3, 7
        V3(I) = CZERO
      ENDDO
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI
     $ * W3))
      V3(3)= DENOM*(-CI )* V1(3)*S2(7)
      V3(4)= DENOM*(-CI )* V1(4)*S2(7)
      V3(5)= DENOM*(-CI )* V1(5)*S2(7)
      V3(6)= DENOM*(-CI )* V1(6)*S2(7)
      CALL MULTIPLY_PROPAGATOR_FACTOR(V3,M3, V3)
      END


