C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,3)
C     
      SUBROUTINE VSV2_0_WW_FD(V1, S2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP
      COMPLEX*16 S2(*)
      COMPLEX*16 TMP3
      COMPLEX*16 V1(*)
      COMPLEX*16 V3(*)
      INTEGER*4 I
      COMPLEX*16 VERTEX
      TMP3 = (V3(3)*V1(3)-V3(4)*V1(4)-V3(5)*V1(5)-V3(6)*V1(6))
      VERTEX = COUP*(-CI * TMP3*S2(7))
      END


