C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,2)
C     
      SUBROUTINE VVS1_2_WW_FD(V1, S3, COUP, M2, W2,V2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP
      REAL*8 M2
      REAL*8 P2(0:3)
      COMPLEX*16 S3(*)
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(7)
      REAL*8 W2
      COMPLEX*16 DENOM
      INTEGER*4 I
      V2(1) = +V1(1)+S3(1)
      V2(2) = +V1(2)+S3(2)
      P2(0) = -DBLE(V2(1))
      P2(1) = -DBLE(V2(2))
      P2(2) = -DIMAG(V2(2))
      P2(3) = -DIMAG(V2(1))
      DO I = 3, 7
        V2(I) = CZERO
      ENDDO
      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
      V2(3)= DENOM*(-CI )* V1(3)*S3(7)
      V2(4)= DENOM*(-CI )* V1(4)*S3(7)
      V2(5)= DENOM*(-CI )* V1(5)*S3(7)
      V2(6)= DENOM*(-CI )* V1(6)*S3(7)
      CALL MULTIPLY_PROPAGATOR_FACTOR(V2,M2, V2)
      END


