C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,1)*Metric(1,2) - P(2,1)*Metric(1,3)
C     
      SUBROUTINE VVV4_3_WW_EL_SMEFT(V1, V2, COUP, M3, W3,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 M3
      REAL*8 OM3
      REAL*8 P1(0:3)
      REAL*8 P3(0:3)
      COMPLEX*16 TMP4
      COMPLEX*16 TMP5
      COMPLEX*16 TMP6
      COMPLEX*16 TMP8
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(6)
      REAL*8 W3
      COMPLEX*16 DENOM
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      OM3 = 0D0
      IF (M3.NE.0D0) OM3=1D0/M3**2
      V3(1) = +V1(1)+V2(1)
      V3(2) = +V1(2)+V2(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))
      TMP4 = (P1(0)*V2(3)-P1(1)*V2(4)-P1(2)*V2(5)-P1(3)*V2(6))
      TMP5 = (P3(0)*V1(3)-P3(1)*V1(4)-P3(2)*V1(5)-P3(3)*V1(6))
      TMP6 = (V2(3)*V1(3)-V2(4)*V1(4)-V2(5)*V1(5)-V2(6)*V1(6))
      TMP8 = (P1(0)*P3(0)-P1(1)*P3(1)-P1(2)*P3(2)-P1(3)*P3(3))
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI
     $ * W3))
      V3(3)= DENOM*(OM3*P3(0)*(-CI*(TMP4*TMP5)+CI*(TMP6*TMP8))+(-CI
     $ *(P1(0)*TMP6)+CI*(V1(3)*TMP4)))
      V3(4)= DENOM*(OM3*P3(1)*(-CI*(TMP4*TMP5)+CI*(TMP6*TMP8))+(-CI
     $ *(P1(1)*TMP6)+CI*(V1(4)*TMP4)))
      V3(5)= DENOM*(OM3*P3(2)*(-CI*(TMP4*TMP5)+CI*(TMP6*TMP8))+(-CI
     $ *(P1(2)*TMP6)+CI*(V1(5)*TMP4)))
      V3(6)= DENOM*(OM3*P3(3)*(-CI*(TMP4*TMP5)+CI*(TMP6*TMP8))+(-CI
     $ *(P1(3)*TMP6)+CI*(V1(6)*TMP4)))
      END


