      COMPLEX*16 FUNCTION AMP_aaWW_SM(P,NHEL)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.9.20, 2024-06-17
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared -- no average over initial
C      state/symmetry factor
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: a a > ta+ ta- NP<=2 @1
C     
            IMPLICIT NONE
C     
C     CONSTANTS
C     
            INTEGER    NEXTERNAL
            PARAMETER (NEXTERNAL=4)
            INTEGER    NWAVEFUNCS, NCOLOR
            PARAMETER (NWAVEFUNCS=5, NCOLOR=1)
            REAL*8     ZERO
            PARAMETER (ZERO=0D0)

C     
C     ARGUMENTS 
C     
            REAL*8 P(0:3,NEXTERNAL)
            INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
            INTEGER I
            REAL*8 CF(NCOLOR,NCOLOR)
            COMPLEX*16 AMP(30), JAMP(NCOLOR)
            COMPLEX*16 W(30,NWAVEFUNCS)
            COMPLEX*16 DUM0,DUM1
            double precision mdl_ww0,mdl_mw0
            DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
            INCLUDE 'coupl.inc'
            include 'wwpars.f'
            include 'egam0.f'
            include 'pol.f'

            DO I=1,4 
                  IC(i) = +1 
            ENDDO                   
      
C     
C     COLOR DATA
C     
            DATA (CF(I,  1),I=  1,  1) /1.000000000000000D+00/
C     1 ColorOne()
C     ----------
C     BEGIN CODE
C     ----------

C     ----------

              mdl_ww0=mdl_ww
              mdl_mw0=mdl_mw
c              mdl_mw=MDL_MW_SMEFT
c              mdl_mw=76d0 0.1576495E-02
c              mdl_ww=0d0
c            print*,mdl_mw0,MDL_MW_SMEFT
c            print*,GC_7053,GC_7253,GC_7313,
c            stop              


              photi=1
              CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
              photi=2
              CALL VXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
              CALL VXXXXX(P(0,3),MDL_MW,NHEL(3),+1*IC(3),W(1,3))



      if(ww_SM)then

C     Amplitude(s) for diagram number 1
              CALL VVVV2_0_WW_unitary
     &        (W(1,1),W(1,2),W(1,4),W(1,3),GC_5,AMP(1))
              CALL VVV1_2_WW_unitary
     &        (W(1,1),W(1,3),-GC_3,MDL_MW,MDL_WW,W(1,5))
C     Amplitude(s) for diagram number 2
              CALL VVV1_0_WW_unitary
     &        (W(1,2),W(1,4),W(1,5),-GC_3,AMP(2))
              CALL VVV1_3_WW_unitary
     &        (W(1,1),W(1,4),-GC_3,MDL_MW,MDL_WW,W(1,5))
C     Amplitude(s) for diagram number 3
              CALL VVV1_0_WW_unitary
     &        (W(1,2),W(1,5),W(1,3),-GC_3,AMP(3))
              JAMP(1) = AMP(1)+AMP(2)+AMP(3)

      else


      photi=1
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      photi=2
      CALL VXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL VXXXXX(P(0,3),MDL_MW,NHEL(3),+1*IC(3),W(1,3))
      CALL VXXXXX(P(0,4),MDL_MW,NHEL(4),+1*IC(4),W(1,4))

C     Amplitude(s) for diagram number 1
      CALL VVVV15_0_WW_EL_SMEFT(W(1,1),W(1,2),W(1,4),W(1,3)
     &,GC_6288,AMP(1))
C     Amplitude(s) for diagram number 2
      CALL VVVV8_0_WW_EL_SMEFT(W(1,1),W(1,2),W(1,4),W(1,3)
     &,GC_5,AMP(2))
      CALL VVS4_3_WW_EL_SMEFT(W(1,1),W(1,2),GC_6548,MDL_MH
     &,MDL_WH,W(1,5))
C     Amplitude(s) for diagram number 3
      CALL VVS3_0_WW_EL_SMEFT(W(1,4),W(1,3),W(1,5),GC_6741,AMP(3))
C     Amplitude(s) for diagram number 4
      CALL VVS4_0_WW_EL_SMEFT(W(1,4),W(1,3),W(1,5),GC_6482,AMP(4))
C     Amplitude(s) for diagram number 5
      CALL VVS3_0_WW_EL_SMEFT(W(1,4),W(1,3),W(1,5),GC_7313,AMP(5))
      CALL VVS4_3_WW_EL_SMEFT(W(1,1),W(1,2),GC_7053,MDL_MH
     &,MDL_WH,W(1,5))
C     Amplitude(s) for diagram number 6
      CALL VVS3_0_WW_EL_SMEFT(W(1,4),W(1,3),W(1,5),GC_6741,AMP(6))
C     Amplitude(s) for diagram number 7
      CALL VVS4_0_WW_EL_SMEFT(W(1,4),W(1,3),W(1,5),GC_6482,AMP(7))
C     Amplitude(s) for diagram number 8
      CALL VVS3_0_WW_EL_SMEFT(W(1,4),W(1,3),W(1,5),GC_7313,AMP(8))
      CALL VVS4_3_WW_EL_SMEFT(W(1,1),W(1,2),GC_7108
     &,MDL_MH,MDL_WH,W(1,5))
C     Amplitude(s) for diagram number 9
      CALL VVS3_0_WW_EL_SMEFT(W(1,4),W(1,3),W(1,5),GC_6741,AMP(9))
C     Amplitude(s) for diagram number 10
      CALL VVS4_0_WW_EL_SMEFT(W(1,4),W(1,3),W(1,5),GC_6482,AMP(10))
C     Amplitude(s) for diagram number 11
      CALL VVS3_0_WW_EL_SMEFT(W(1,4),W(1,3),W(1,5),GC_7313,AMP(11))
      CALL VVV8_2_WW_EL_SMEFT(W(1,1),W(1,3),GC_6286,MDL_MW
     &,MDL_WW,W(1,5))
C     Amplitude(s) for diagram number 12
      CALL VVV8_0_WW_EL_SMEFT(W(1,2),W(1,4),W(1,5),GC_6286,AMP(12))
C     Amplitude(s) for diagram number 13
      CALL VVV7_0_WW_EL_SMEFT(W(1,2),W(1,4),W(1,5),GC_3,AMP(13))
C     Amplitude(s) for diagram number 14
      CALL VVV4_0_WW_EL_SMEFT(W(1,2),W(1,4),W(1,5),GC_7253,AMP(14))
      CALL VVV7_2_WW_EL_SMEFT(W(1,1),W(1,3),GC_3,MDL_MW
     &,MDL_WW,W(1,5))
C     Amplitude(s) for diagram number 15
      CALL VVV8_0_WW_EL_SMEFT(W(1,2),W(1,4),W(1,5),GC_6286,AMP(15))
C     Amplitude(s) for diagram number 16
      CALL VVV7_0_WW_EL_SMEFT(W(1,2),W(1,4),W(1,5),GC_3,AMP(16))
C     Amplitude(s) for diagram number 17
      CALL VVV4_0_WW_EL_SMEFT(W(1,2),W(1,4),W(1,5),GC_7253,AMP(17))
      CALL VVV4_2_WW_EL_SMEFT(W(1,1),W(1,3),GC_7253
     &,MDL_MW,MDL_WW,W(1,5))
C     Amplitude(s) for diagram number 18
      CALL VVV8_0_WW_EL_SMEFT(W(1,2),W(1,4),W(1,5),GC_6286,AMP(18))
C     Amplitude(s) for diagram number 19
      CALL VVV7_0_WW_EL_SMEFT(W(1,2),W(1,4),W(1,5),GC_3,AMP(19))
C     Amplitude(s) for diagram number 20
      CALL VVV4_0_WW_EL_SMEFT(W(1,2),W(1,4),W(1,5),GC_7253,AMP(20))
      CALL VVV8_3_WW_EL_SMEFT(W(1,1),W(1,4),GC_6286,MDL_MW
     &      ,MDL_WW,W(1,5))
C     Amplitude(s) for diagram number 21
      CALL VVV8_0_WW_EL_SMEFT(W(1,2),W(1,5),W(1,3),GC_6286,AMP(21))
C     Amplitude(s) for diagram number 22
      CALL VVV7_0_WW_EL_SMEFT(W(1,2),W(1,5),W(1,3),GC_3,AMP(22))
C     Amplitude(s) for diagram number 23
      CALL VVV4_0_WW_EL_SMEFT(W(1,2),W(1,5),W(1,3),GC_7253,AMP(23))
      CALL VVV7_3_WW_EL_SMEFT(W(1,1),W(1,4),GC_3
     &,MDL_MW,MDL_WW,W(1,5))
C     Amplitude(s) for diagram number 24
      CALL VVV8_0_WW_EL_SMEFT(W(1,2),W(1,5),W(1,3),GC_6286,AMP(24))
C     Amplitude(s) for diagram number 25
      CALL VVV7_0_WW_EL_SMEFT(W(1,2),W(1,5),W(1,3),GC_3,AMP(25))
C     Amplitude(s) for diagram number 26
      CALL VVV4_0_WW_EL_SMEFT(W(1,2),W(1,5),W(1,3),GC_7253,AMP(26))
      CALL VVV4_3_WW_EL_SMEFT(W(1,1),W(1,4),GC_7253,MDL_MW
     &      ,MDL_WW,W(1,5))
C     Amplitude(s) for diagram number 27
      CALL VVV8_0_WW_EL_SMEFT(W(1,2),W(1,5),W(1,3),GC_6286,AMP(27))
C     Amplitude(s) for diagram number 28
      CALL VVV7_0_WW_EL_SMEFT(W(1,2),W(1,5),W(1,3),GC_3,AMP(28))
C     Amplitude(s) for diagram number 29
      CALL VVV4_0_WW_EL_SMEFT(W(1,2),W(1,5),W(1,3),GC_7253,AMP(29))

      JAMP(1)=+AMP(1)+AMP(2)+AMP(3)+AMP(4)+AMP(5)+AMP(6)+AMP(7)+AMP(8)
     $ +AMP(9)+AMP(10)+AMP(11)+AMP(12)+AMP(13)+AMP(14)+AMP(15)+AMP(16)
     $ +AMP(17)+AMP(18)+AMP(19)+AMP(20)+AMP(21)+AMP(22)+AMP(23)+AMP(24)
     $ +AMP(25)+AMP(26)+AMP(27)+AMP(28)+AMP(29)

      JAMP(1)=AMP(2)+AMP(16)+AMP(25) 

      if(ww_noSM)JAMP(1)=0d0

      JAMP(1)=JAMP(1)+AMP(1)+AMP(3)+AMP(6)+AMP(9)+AMP(13)+AMP(15)
     &      +AMP(17)+AMP(19)+AMP(22)+AMP(24)+AMP(26)+AMP(28)

      if(ww_NP2)then

      JAMP(1)=JAMP(1)+AMP(4)+AMP(5)+AMP(7)+AMP(8)+AMP(10)+AMP(11)
     &     +AMP(12)+AMP(14)+AMP(18)+AMP(20)+AMP(21)+AMP(23)+AMP(27)
     &      +AMP(29)

      endif

c      do i=1,29
c       print*,i,amp(i)
c      enddo 
c      print*,GC_6288

      endif

ccccccccccccccc

C     Amplitude(s) for diagram number 1
c         CALL VVVV2_VVSS1_0_WW_FD
c       & (W(1,1),W(1,2),W(1,4),W(1,3),GC_5,GC_6,AMP(1))
c         CALL VVV1_VVS1_VSV2_VSS1_2_WW_FD(W(1,1),W(1,3),-GC_3,GC_74,-GC_74
c       & ,GC_3,MDL_MW,MDL_WW,W(1,5))
c   C     Amplitude(s) for diagram number 2
c         CALL VVV1_VVS1_VSV2_VSS1_0_WW_FD(W(1,2),W(1,4),W(1,5),-GC_3,GC_74
c       $ ,-GC_74,GC_3,AMP(2))
c         CALL VVV1_VVS1_VSV2_VSS1_3_WW_FD(W(1,1),W(1,4),-GC_3,GC_74,-GC_74
c       & ,GC_3,MDL_MW,MDL_WW,W(1,5))
c   C     Amplitude(s) for diagram number 3
c         CALL VVV1_VVS1_VSV2_VSS1_0_WW_FD(W(1,2),W(1,5),W(1,3),-GC_3,GC_74
c       $ ,-GC_74,GC_3,AMP(3))
c         JAMP(1) = AMP(1)+AMP(2)+AMP(3)

            AMP_aaWW_SM=JAMP(1)

            mdl_ww=mdl_ww0
            mdl_mw=mdl_mw0

            END
      
         
      
