      SUBROUTINE SMATRIX_gamq_gamgamq(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.6.2, 2025-03-19
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: a u > a a u WEIGHTED<=6 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=32)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/PROCESS_NHEL_gamq_gamgamq/NHEL
      REAL*8 T
      REAL*8 MATRIX_gamq_gamgamq
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE_gamq_gamgamq/USERHEL
      DATA USERHEL/-1/
      LOGICAL HELRESET_gamq_gamgamq
      COMMON/HELRESET_gamq_gamgamq/HELRESET_gamq_gamgamq
      DATA HELRESET_gamq_gamgamq/.TRUE./

      DATA (NHEL(I,   1),I=1,5) /-1, 1,-1,-1,-1/
      DATA (NHEL(I,   2),I=1,5) /-1, 1,-1,-1, 1/
      DATA (NHEL(I,   3),I=1,5) /-1, 1,-1, 1,-1/
      DATA (NHEL(I,   4),I=1,5) /-1, 1,-1, 1, 1/
      DATA (NHEL(I,   5),I=1,5) /-1, 1, 1,-1,-1/
      DATA (NHEL(I,   6),I=1,5) /-1, 1, 1,-1, 1/
      DATA (NHEL(I,   7),I=1,5) /-1, 1, 1, 1,-1/
      DATA (NHEL(I,   8),I=1,5) /-1, 1, 1, 1, 1/
      DATA (NHEL(I,   9),I=1,5) /-1,-1,-1,-1,-1/
      DATA (NHEL(I,  10),I=1,5) /-1,-1,-1,-1, 1/
      DATA (NHEL(I,  11),I=1,5) /-1,-1,-1, 1,-1/
      DATA (NHEL(I,  12),I=1,5) /-1,-1,-1, 1, 1/
      DATA (NHEL(I,  13),I=1,5) /-1,-1, 1,-1,-1/
      DATA (NHEL(I,  14),I=1,5) /-1,-1, 1,-1, 1/
      DATA (NHEL(I,  15),I=1,5) /-1,-1, 1, 1,-1/
      DATA (NHEL(I,  16),I=1,5) /-1,-1, 1, 1, 1/
      DATA (NHEL(I,  17),I=1,5) / 1, 1,-1,-1,-1/
      DATA (NHEL(I,  18),I=1,5) / 1, 1,-1,-1, 1/
      DATA (NHEL(I,  19),I=1,5) / 1, 1,-1, 1,-1/
      DATA (NHEL(I,  20),I=1,5) / 1, 1,-1, 1, 1/
      DATA (NHEL(I,  21),I=1,5) / 1, 1, 1,-1,-1/
      DATA (NHEL(I,  22),I=1,5) / 1, 1, 1,-1, 1/
      DATA (NHEL(I,  23),I=1,5) / 1, 1, 1, 1,-1/
      DATA (NHEL(I,  24),I=1,5) / 1, 1, 1, 1, 1/
      DATA (NHEL(I,  25),I=1,5) / 1,-1,-1,-1,-1/
      DATA (NHEL(I,  26),I=1,5) / 1,-1,-1,-1, 1/
      DATA (NHEL(I,  27),I=1,5) / 1,-1,-1, 1,-1/
      DATA (NHEL(I,  28),I=1,5) / 1,-1,-1, 1, 1/
      DATA (NHEL(I,  29),I=1,5) / 1,-1, 1,-1,-1/
      DATA (NHEL(I,  30),I=1,5) / 1,-1, 1,-1, 1/
      DATA (NHEL(I,  31),I=1,5) / 1,-1, 1, 1,-1/
      DATA (NHEL(I,  32),I=1,5) / 1,-1, 1, 1, 1/
      DATA IDEN/24/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL_gamq_gamgamq/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL IS_BORN_HEL_SELECTED

C     ----------
C     Check if helreset mode is on
C     ---------
      IF (HELRESET_gamq_gamgamq) THEN
        NTRY = 0
        DO I=1,NCOMB
          GOODHEL(I) = .FALSE.
        ENDDO
        HELRESET_gamq_gamgamq = .FALSE.
      ENDIF

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
c            if(ihel.eq.2)then
            T=matrix_gamq_gamgamq(P ,NHEL(1,IHEL),JC(1))
c            print*,ihel,t
c            t=1d0
c            else
c            t=0d0
c            endif
            IF(POLARIZATIONS(0,0).EQ.-1.OR.IS_BORN_HEL_SELECTED(IHEL))
     $        THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION MATRIX_gamq_gamgamq(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.6.2, 2025-03-19
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared -- no average over initial
C      state/symmetry factor
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: a u > a a u WEIGHTED<=6 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=6)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=9, NCOLOR=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      INTEGER CF_INDEX
      INTEGER CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER DENOM
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR), TMP_JAMP(0)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      logical scpol_save
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
      include 'egam0.f'

C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  1) /3/
C     1 T(5,2)
C     ----------
C     BEGIN CODE
C     ----------

      scpol_save=scpol

      photi=2
      zcalc=.false.

c      print*,nhel(1),nhel(2),nhel(3),nhel(4),nhel(5)
c      print*,ic(1),ic(2),ic(3),ic(4),ic(5)

c      print*,'test1'

      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      zcalc=.false.
      CALL IXXXXX(P(0,2),ZERO,NHEL(2),+1*IC(2),W(1,2))

c      print*,'test2'

      if(scpol_save)scpol=.false.

      CALL VXXXXX(P(0,3),ZERO,NHEL(3),+1*IC(3),W(1,3))
      CALL VXXXXX(P(0,4),ZERO,NHEL(4),+1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,5))

      if(scpol_save)scpol=.true.

c      print*,'test3'

      CALL FFV1_2_ion_em(W(1,2),W(1,1),GC_2,ZERO,ZERO,W(1,6))
      CALL FFV1_1_ion_em(W(1,5),W(1,3),GC_2,ZERO,ZERO,W(1,7))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0_ion_em(W(1,6),W(1,7),W(1,4),GC_2,AMP(1))
      CALL FFV1_1_ion_em(W(1,5),W(1,4),GC_2,ZERO,ZERO,W(1,8))

c      print*,'test4'

C     Amplitude(s) for diagram number 2
      CALL FFV1_0_ion_em(W(1,6),W(1,8),W(1,3),GC_2,AMP(2))

c      print*,'test5'

      CALL FFV1_1_ion_em(W(1,5),W(1,1),GC_2,ZERO,ZERO,W(1,6))
      CALL FFV1_2_ion_em(W(1,2),W(1,3),GC_2,ZERO,ZERO,W(1,5))

c      print*,'test6'

C     Amplitude(s) for diagram number 3
      CALL FFV1_0_ion_em(W(1,5),W(1,6),W(1,4),GC_2,AMP(3))
      CALL FFV1_2_ion_em(W(1,2),W(1,4),GC_2,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 4
      CALL FFV1_0_ion_em(W(1,9),W(1,6),W(1,3),GC_2,AMP(4))
C     Amplitude(s) for diagram number 5
      CALL FFV1_0_ion_em(W(1,5),W(1,8),W(1,1),GC_2,AMP(5))
C     Amplitude(s) for diagram number 6
      CALL FFV1_0_ion_em(W(1,9),W(1,7),W(1,1),GC_2,AMP(6))
      JAMP(1) = AMP(1)+AMP(2)+AMP(3)+AMP(4)+AMP(5)+AMP(6)

c      print*,jamp(1)

c      print*,nhel(1),nhel(2),nhel(3),nhel(4),nhel(5)
c      print*,amp(1),amp(2),amp(3),amp(4),amp(5),amp(6)
c      print*,''

      matrix_gamq_gamgamq = 0.D0
      CF_INDEX = 0
      DO I = 1, NCOLOR
        ZTEMP = (0D0,0D0)
        DO J = I, NCOLOR
          CF_INDEX = CF_INDEX +1
          ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J)
        ENDDO
        matrix_gamq_gamgamq = matrix_gamq_gamgamq
     &      +REAL(ZTEMP*DCONJG(JAMP(I)))
      ENDDO
      matrix_gamq_gamgamq = matrix_gamq_gamgamq / DENOM

c      print*,matrix_gamq_gamgamq
c      print*,''

      END

      COMPLEX*16  FUNCTION AMP_gamq_gamgamq(P,NHEL)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.6.2, 2025-03-19
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared -- no average over initial
C      state/symmetry factor
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: a u > a a u WEIGHTED<=6 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=6)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=9, NCOLOR=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      INTEGER CF_INDEX
      INTEGER CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER DENOM
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR), TMP_JAMP(0)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
      include 'egam0.f'

C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  1) /3/
C     1 T(5,2)
C     ----------
C     BEGIN CODE
C     ----------

      DO I=1,5 
          IC(i) = +1 
      ENDDO   

      photi=2
      zcalc=.false.

c      print*,'test1'

      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      zcalc=.false.
      CALL IXXXXX(P(0,2),ZERO,NHEL(2),+1*IC(2),W(1,2))

c      print*,'test2'

      zcalc=.true.
      CALL VXXXXX(P(0,3),ZERO,NHEL(3),+1*IC(3),W(1,3))
      zcalc=.false.     
      CALL VXXXXX(P(0,4),ZERO,NHEL(4),+1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,5))

c      print*,'test3'

      CALL FFV1_2_ion_em(W(1,2),W(1,1),GC_2,ZERO,ZERO,W(1,6))
      CALL FFV1_1_ion_em(W(1,5),W(1,3),GC_2,ZERO,ZERO,W(1,7))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0_ion_em(W(1,6),W(1,7),W(1,4),GC_2,AMP(1))
      CALL FFV1_1_ion_em(W(1,5),W(1,4),GC_2,ZERO,ZERO,W(1,8))

c      print*,'test4'

C     Amplitude(s) for diagram number 2
      CALL FFV1_0_ion_em(W(1,6),W(1,8),W(1,3),GC_2,AMP(2))

c      print*,'test5'

      CALL FFV1_1_ion_em(W(1,5),W(1,1),GC_2,ZERO,ZERO,W(1,6))
      CALL FFV1_2_ion_em(W(1,2),W(1,3),GC_2,ZERO,ZERO,W(1,5))

c      print*,'test6'

C     Amplitude(s) for diagram number 3
      CALL FFV1_0_ion_em(W(1,5),W(1,6),W(1,4),GC_2,AMP(3))
      CALL FFV1_2_ion_em(W(1,2),W(1,4),GC_2,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 4
      CALL FFV1_0_ion_em(W(1,9),W(1,6),W(1,3),GC_2,AMP(4))
C     Amplitude(s) for diagram number 5
      CALL FFV1_0_ion_em(W(1,5),W(1,8),W(1,1),GC_2,AMP(5))
C     Amplitude(s) for diagram number 6
      CALL FFV1_0_ion_em(W(1,9),W(1,7),W(1,1),GC_2,AMP(6))
      JAMP(1) = AMP(1)+AMP(2)+AMP(3)+AMP(4)+AMP(5)+AMP(6)

c      print*,amp(1),amp(2),amp(3),amp(4),amp(5),amp(6)

      AMP_gamq_gamgamq=JAMP(1)

c      print*,AMP_gamq_gamgamq

      END
