ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION MDL_SQRT__AS,MDL_G__EXP__2,MDL_CONJG__CKM3X3
     $ ,MDL_CONJG__CKM1X1,MDL_CKM3X3,MDL_MZ__EXP__2,MDL_MZ__EXP__4
     $ ,MDL_SQRT__2,MDL_MH__EXP__2,MDL_AEW,MDL_SQRT__AEW,MDL_EE
     $ ,MDL_MW__EXP__2,MDL_SW2,MDL_CW,MDL_SQRT__SW2,MDL_SW,MDL_G1
     $ ,MDL_GW,MDL_VEV,MDL_VEV__EXP__2,MDL_LAM,MDL_YB,MDL_YT,MDL_YTAU
     $ ,MDL_MUH,MDL_EE__EXP__2,MDL_SW__EXP__2,MDL_CW__EXP__2,AEWM1
     $ ,MDL_GF,AS,MDL_YMB,MDL_YMT,MDL_YMTAU,mdl_vevhat__exp__3
     $ ,mdl_vevhat__exp__2,mdl_vevhat,MDL_STH__EXP__3,MDL_STH__EXP__2
     $ ,MDL_STH,MDL_LAMBDASMEFT__EXP__2,MDL_CTH__EXP__2,MDL_CTH
     $ ,MDL_CHWB,MDL_CHW,MDL_CHB,mdl_sqrt__sth2,mdl_sqrt__gf
     $ ,mdl_nb__2__exp__0_25,mdl_cth__exp__3,mdl_sth2,MDL_CW_SMEFT
     $ ,MDL_DMZ2,MDL_DGW,MDL_MWSM,MDL_DMW

      COMMON/PARAMS_R/ MDL_SQRT__AS,MDL_G__EXP__2,MDL_CONJG__CKM3X3
     $ ,MDL_CONJG__CKM1X1,MDL_CKM3X3,MDL_MZ__EXP__2,MDL_MZ__EXP__4
     $ ,MDL_SQRT__2,MDL_MH__EXP__2,MDL_AEW,MDL_SQRT__AEW,MDL_EE
     $ ,MDL_MW__EXP__2,MDL_SW2,MDL_CW,MDL_SQRT__SW2,MDL_SW,MDL_G1
     $ ,MDL_GW,MDL_VEV,MDL_VEV__EXP__2,MDL_LAM,MDL_YB,MDL_YT,MDL_YTAU
     $ ,MDL_MUH,MDL_EE__EXP__2,MDL_SW__EXP__2,MDL_CW__EXP__2,AEWM1
     $ ,MDL_GF,AS,MDL_YMB,MDL_YMT,MDL_YMTAU,mdl_vevhat__exp__3
     $ ,mdl_vevhat__exp__2,mdl_vevhat,MDL_STH__EXP__3,MDL_STH__EXP__2
     $ ,MDL_STH,MDL_LAMBDASMEFT__EXP__2,MDL_CTH__EXP__2,MDL_CTH
     $ ,MDL_CHWB,MDL_CHW,MDL_CHB,mdl_sqrt__sth2,mdl_sqrt__gf
     $ ,mdl_nb__2__exp__0_25,mdl_cth__exp__3,mdl_sth2,MDL_CW_SMEFT
     $ ,MDL_DMZ2,MDL_DGW,MDL_MWSM,MDL_DMW

      DOUBLE COMPLEX MDL_COMPLEXI,MDL_I1X33,MDL_I2X33,MDL_I3X33
     $ ,MDL_I4X33

      COMMON/PARAMS_C/ MDL_COMPLEXI,MDL_I1X33,MDL_I2X33,MDL_I3X33
     $ ,MDL_I4X33


